const QuoteActionTypes = {
  FETCH_QUOTES_LOADING: "FETCH_QUOTES_LOADING",
  FETCH_QUOTES_SUCCESS: "FETCH_QUOTES_SUCCESS",
  FETCH_QUOTES_ERROR: "FETCH_QUOTES_FAILURE",

  SET_QUOTES_DATA_BASE: "SET_QUOTES_DATA_BASE",

  SET_LIKED_QUOTE: "SET_LIKED_QUOTE",

  SET_INSPIRATIONAL_QUOTE: "SET_INSPIRATIONAL_QUOTE",
  SET_INSIGHTFUL_QUOTE: "SET_INSIGHTFUL_QUOTE",

  ADD_QUOTE_CARD: "ADD_QUOTE_CARD",
};

export default QuoteActionTypes;
